[versions]
kotlinx-datetime = "0.7.1"
kotlinx-io = "0.8.2"
ktor = "3.3.3"

[libraries]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
ktor-client = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
